[package]
name = "dcrypt-params"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Constant values for dcrypt library"
repository.workspace = true
license.workspace = true
publish = true


[package.metadata.release]
publish = true